# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestpassport',
            old_name='author',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='guestpassport',
            name='passphoto',
            field=models.ImageField(default='static/', upload_to='static/'),
        ),
    ]
