# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20160503_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestpassport',
            name='passphoto',
        ),
        migrations.AddField(
            model_name='guestpassport',
            name='passportphoto',
            field=models.ImageField(default='static/none.jpg', upload_to='static/'),
        ),
    ]
